package org.dark.keyboard.shared.xml

import org.dark.keyboard.shared.model.KeyModel
import org.dark.keyboard.shared.model.LayoutModel

/**
 * Generates Android keyboard XML from LayoutModel.
 * 
 * Produces XML compatible with DarkKeyboard's kbd_*.xml format:
 * - Proper <Keyboard> root with percentage-based dimensions
 * - <Row> grouping by Y position
 * - <Key> elements with all attributes
 * - Proper formatting and indentation
 */
object XmlLayoutGenerator {
    
    /**
     * Generate Android keyboard XML from LayoutModel.
     * 
     * @param layout The layout to convert
     * @param screenWidth Reference screen width (default 1080)
     * @return Formatted XML string ready for Custom Layout editor
     */
    fun generate(layout: LayoutModel, screenWidth: Int = 1080): String {
        val sb = StringBuilder()
        
        // XML header
        sb.appendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
        sb.appendLine("<!--")
        sb.appendLine("${layout.name}")
        sb.appendLine("Generated by DarkKeyboard Editor")
        sb.appendLine("-->")
        
        // Group keys by rows (same Y position)
        val rows = groupKeysByRows(layout.keys)
        
        // Calculate base dimensions
        val baseKeyWidth = calculateBaseKeyWidth(rows, screenWidth)
        val baseKeyHeight = if (rows.isNotEmpty()) rows[0].firstOrNull()?.height ?: 160 else 160
        
        // <Keyboard> tag
        sb.appendLine("<Keyboard")
        sb.appendLine("    xmlns:android=\"http://schemas.android.com/apk/res-auto\"")
        sb.appendLine("    android:keyWidth=\"${formatPercentage(baseKeyWidth, screenWidth)}\"")
        sb.appendLine("    android:horizontalGap=\"0px\"")
        sb.appendLine("    android:verticalGap=\"@dimen/key_bottom_gap\">")
        sb.appendLine()
        
        // Generate rows
        rows.forEachIndexed { index, rowKeys ->
            generateRow(sb, rowKeys, index == 0, index == rows.size - 1, baseKeyWidth, screenWidth)
            sb.appendLine()
        }
        
        sb.appendLine("</Keyboard>")
        
        return sb.toString()
    }
    
    private fun groupKeysByRows(keys: List<KeyModel>): List<List<KeyModel>> {
        // Group by Y position with tolerance (keys within 5px are same row)
        val tolerance = 5
        val grouped = mutableListOf<MutableList<KeyModel>>()
        
        keys.sortedBy { it.y }.forEach { key ->
            val existingRow = grouped.find { row ->
                val firstKey = row.firstOrNull()
                firstKey != null && kotlin.math.abs(firstKey.y - key.y) <= tolerance
            }
            
            if (existingRow != null) {
                existingRow.add(key)
            } else {
                grouped.add(mutableListOf(key))
            }
        }
        
        // Sort keys within each row by X position
        return grouped.map { row -> row.sortedBy { it.x } }
    }
    
    private fun calculateBaseKeyWidth(rows: List<List<KeyModel>>, screenWidth: Int): Int {
        // Find most common key width (mode)
        if (rows.isEmpty()) return screenWidth / 10
        
        val widths = rows.flatten().map { it.width }
        val widthCounts = widths.groupingBy { it }.eachCount()
        return widthCounts.maxByOrNull { it.value }?.key ?: (screenWidth / 10)
    }
    
    private fun generateRow(
        sb: StringBuilder,
        keys: List<KeyModel>,
        isFirst: Boolean,
        isLast: Boolean,
        baseKeyWidth: Int,
        screenWidth: Int
    ) {
        // Determine row attributes
        val rowAttrs = mutableListOf<String>()
        
        if (isFirst && keys.any { it.edgeFlags and KeyModel.EDGE_TOP != 0 }) {
            rowAttrs.add("android:rowEdgeFlags=\"top\"")
        }
        if (isLast && keys.any { it.edgeFlags and KeyModel.EDGE_BOTTOM != 0 }) {
            rowAttrs.add("android:rowEdgeFlags=\"bottom\"")
        }
        
        // Check if this is an extension row (numbers row typically)
        val isExtension = keys.size == 10 && keys.all { it.label.length == 1 && it.label[0].isDigit() }
        if (isExtension) {
            rowAttrs.add("android:extension=\"true\"")
        }
        
        // Row opening tag
        if (rowAttrs.isNotEmpty()) {
            sb.appendLine("    <Row ${rowAttrs.joinToString(" ")}>")
        } else {
            sb.appendLine("    <Row>")
        }
        
        // Generate keys
        keys.forEach { key ->
            generateKey(sb, key, baseKeyWidth, screenWidth)
        }
        
        sb.appendLine("    </Row>")
    }
    
    private fun generateKey(
        sb: StringBuilder,
        key: KeyModel,
        baseKeyWidth: Int,
        screenWidth: Int
    ) {
        sb.append("        <Key")
        
        // Code (always include for modifiers and special keys)
        val codeAttr = formatKeyCode(key.code)
        val isSpecialKey = key.code < 0 || key.isModifier
        
        if (isSpecialKey || shouldIncludeCode(key)) {
            sb.append(" android:codes=\"$codeAttr\"")
        }
        
        // Label (include if not empty, even for modifiers with visible symbols)
        if (key.label.isNotEmpty()) {
            sb.append(" android:keyLabel=\"${escapeXml(key.label)}\"")
        }
        
        // Shift label
        if (key.shiftLabel != null && key.shiftLabel != key.label.uppercase()) {
            sb.append(" android:shiftLabel=\"${escapeXml(key.shiftLabel!!)}\"")
        }
        
        // Popup characters
        if (key.popupKeys.isNotEmpty()) {
            val escapedPopups = key.popupKeys.joinToString("") { escapeXml(it) }
            sb.append(" android:popupCharacters=\"$escapedPopups\"")
            sb.append(" android:popupKeyboard=\"@xml/kbd_popup_template\"")
        }
        
        // Width (only if different from base)
        if (key.width != baseKeyWidth) {
            sb.append(" android:keyWidth=\"${formatPercentage(key.width, screenWidth)}\"")
        }
        
        // Modifiers (Delete should also be marked as modifier for Android compatibility)
        val shouldBeModifier = key.isModifier || key.code == KeyModel.CODE_DELETE
        if (shouldBeModifier) {
            sb.append(" android:isModifier=\"true\"")
        }
        if (key.isSticky) {
            sb.append(" android:isSticky=\"true\"")
        }
        if (key.repeatable) {
            sb.append(" android:isRepeatable=\"true\"")
        }
        
        // Edge flags
        val edgeFlag = formatEdgeFlags(key.edgeFlags)
        if (edgeFlag.isNotEmpty()) {
            sb.append(" android:keyEdgeFlags=\"$edgeFlag\"")
        }
        
        sb.appendLine(" />")
    }
    
    private fun shouldIncludeCode(key: KeyModel): Boolean {
        // Always include codes for modifiers
        if (key.isModifier || key.code < 0) return true
        
        // Always include for common special keys (Space, Enter, Tab, etc)
        if (key.code == 32 || key.code == 10 || key.code == 9) return true
        
        // Don't include code if it matches the label's first character AND it's alphanumeric
        val labelChar = key.label.firstOrNull()
        if (labelChar != null && labelChar.code == key.code && (labelChar.isLetterOrDigit() || labelChar in ".,;:'\"")) {
            return false
        }
        
        // Include code for all other cases
        return true
    }
    
    private fun formatKeyCode(code: Int): String {
        // Use numeric codes, not @integer references (custom layout loads plain XML)
        return code.toString()
    }
    
    private fun formatPercentage(pixels: Int, screenWidth: Int): String {
        val percentage = (pixels.toFloat() / screenWidth * 100)
        
        // Round to nearest integer if close enough (within 0.1%)
        val rounded = kotlin.math.round(percentage)
        if (kotlin.math.abs(percentage - rounded) < 0.1f) {
            return "${rounded.toInt()}%p"
        }
        
        // Otherwise use 1 decimal place
        val oneDecimal = (percentage * 10).toInt() / 10.0
        return "$oneDecimal%p"
    }
    
    private fun formatEdgeFlags(flags: Int): String {
        // Don't include row-level edge flags in individual keys
        // Only include left/right flags for first/last keys in row
        val parts = mutableListOf<String>()
        if (flags and KeyModel.EDGE_LEFT != 0) parts.add("left")
        if (flags and KeyModel.EDGE_RIGHT != 0) parts.add("right")
        // Skip top/bottom - those are handled by rowEdgeFlags
        return parts.joinToString("|")
    }
    
    private fun escapeXml(text: String): String {
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "\\'")
            .replace("@", "\\@")
            .replace("#", "\\#")
    }
}
